<?php
$map_info = array (
"1-1" => array("level_height" => 4,"level_width" => 15,"height_crop" => 17,"width_extra" => $osd_width),
"1-2" => array("level_height" => 4,"level_width" => 15,"height_crop" => 17,"width_extra" => $osd_width),
"1-3" => array("level_height" => 4,"level_width" =>  7,"height_crop" => 17,"width_extra" => $osd_width+15),
"2-1" => array("level_height" => 6,"level_width" =>  9,"height_crop" => 17,"width_extra" => $osd_width),
"2-2" => array("level_height" => 3,"level_width" => 11,"height_crop" => -80,"width_extra" => $osd_width),
"3-1" => array("level_height" => 4,"level_width" => 15,"height_crop" => 17,"width_extra" => $osd_width),
"3-2" => array("level_height" => 4,"level_width" => 15,"height_crop" => 17,"width_extra" => $osd_width),
"3-3" => array("level_height" => 9,"level_width" =>  7,"height_crop" => 25,"width_extra" => $osd_width),
"4-1" => array("level_height" => 19,"level_width" => 3,"height_crop" => 17+24,"width_extra" => $osd_width),
"4-2" => array("level_height" => 4,"level_width" => 15,"height_crop" => 17,"width_extra" => $osd_width),
"4-3" => array("level_height" => 38,"level_width" => 1,"height_crop" => -31,"width_extra" => $osd_width-1),
"4-4" => array("level_height" => 4,"level_width" =>  5,"height_crop" => 17,"width_extra" => $osd_width),
"5-1" => array("level_height" => 4,"level_width" =>  3,"height_crop" => 17+24,"width_extra" => $osd_width),
"5-2" => array("level_height" => 9,"level_width" =>  7,"height_crop" => 25,"width_extra" => $osd_width),
"6-1" => array("level_height" => 4,"level_width" =>  7,"height_crop" => 17,"width_extra" => $osd_width+15),
"6-2" => array("level_height" => 4,"level_width" => 15,"height_crop" => 17,"width_extra" => $osd_width),
"6-3" => array("level_height" => 2,"level_width" =>  7,"height_crop" => 17,"width_extra" => $osd_width+15),
"6-4" => array("level_height" => 9,"level_width" =>  3,"height_crop" => 25,"width_extra" => $osd_width),
"6-5" => array("level_height" => 6,"level_width" =>  9,"height_crop" => 17,"width_extra" => $osd_width),
"6-6" => array("level_height" => 6,"level_width" =>  3,"height_crop" => -32,"width_extra" => $osd_width*3+15),
"6-7" => array("level_height" => 4,"level_width" =>  7,"height_crop" => 17,"width_extra" => $osd_width),
"6-8" => array("level_height" => 9,"level_width" =>  3,"height_crop" => 25,"width_extra" => $osd_width),
"6-9" => array("level_height" => 4,"level_width" =>  7,"height_crop" => 17,"width_extra" => $osd_width),
"7-1" => array("level_height" => 6,"level_width" =>  9,"height_crop" => 0,"width_extra" => $osd_width),
"7-2" => array("level_height" => 4,"level_width" => 15,"height_crop" => 17,"width_extra" => $osd_width),
);
